### ISSUE TITLE
problems with Web sub stack

### ISSUE THREAD

**Issue by mteichtahl** [aws-samples/aws-refarch-wordpress#56]
I have tried to kick off the stac creation. Everything looks fine until the stack rolls back with the following error. 

It feels like the instances aren't given enough time to start up. 

Any guidance appreciated. 

```
Received 1 SUCCESS signal(s) out of 2. Unable to satisfy 100% MinSuccessfulInstancesPercent requirement
19:44:21 UTC+1100	UPDATE_IN_PROGRESS	AWS::AutoScaling::AutoScalingGroup	WebAutoScalingGroup	Failed to receive 1 resource signal(s) for the current batch. Each resource signal timeout is counted as a FAILURE.
19:41:44 UTC+1100	CREATE_IN_PROGRESS	AWS::AutoScaling::AutoScalingGroup	WebAutoScalingGroup	Received SUCCESS signal with UniqueId i-0b3ce92aef06b21fb
19:39:20 UTC+1100	CREATE_IN_PROGRESS	AWS::AutoScaling::AutoScalingGroup	WebAutoScalingGroup	Resource creation Initiated
```

**Comment by mteichtahl** [comment]
more detail on the actual failure below

```
+ mount -t nfs4 -o nfsve[   69.069151] RPC: Registered udp transport module.
rs=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2 fs-3295eed3.efs.us-east-1.amazonaws.com:/ /var/www/wordpress
[   69.095800] RPC: Registered tcp transport module.
[   69.100105] RPC: Registered tcp NFSv4.1 backchannel transport module.
[   69.111276] FS-Cache: Netfs 'nfs' registered for caching
[   69.119110] Key type dns_resolver registered
[   69.129388] NFS: Registering the id_resolver key type
[   69.134074] Key type id_resolver registered
[   69.138072] Key type id_legacy registered
+ /opt/aws/bin/cfn-init --configsets deploy_webserver --verbose --stack wordpress-web-YHC7G4NGDC37 --resource WebLaunchConfiguration70 --region us-east-1
Traceback (most recent call last):
  File "/usr/lib64/python2.7/logging/__init__.py", line 891, in emit
    stream.write(fs % msg.encode("UTF-8"))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 49: ordinal not in range(128)
Logged from file util.py, line 476
Traceback (most recent call last):
  File "/usr/lib64/python2.7/logging/__init__.py", line 891, in emit
    stream.write(fs % msg.encode("UTF-8"))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 72: ordinal not in range(128)
Logged from file util.py, line 476
Error occurred during build: Command install_wordpress failed
Jan 07 09:26:22 cloud-init[2906]: util.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/part-001 [1]
Jan 07 09:26:22 cloud-init[2906]: cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
Jan 07 09:26:22 cloud-init[2906]: util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_scripts_user.pyc'>) failed
ci-info: ++++++Authorized keys from /home/ec2-user/.ssh/authorized_keys for user ec2-user+++++++
ci-info:  Keytype                 Fingerprint (md5)                 Options       Comment       
ci-info:  ssh-rsa  5b:9a:2c:0c:bb:11:24:08:af:c6:5d:50:4d:2d:2b:cf     -     teichtahlWordPress 
ec2: 
ec2: #############################################################
ec2: -----BEGIN SSH HOST KEY FINGERPRINTS-----
ec2: 1024 SHA256:o4EsF/GLu36QaFGV5jn3oxIhE+UZte0l+dT9yDrkTx0 root@ip-10-0-1-111 (DSA)
ec2: 256 SHA256:sJvQls4B6jqZMX/OgqxUCbS1Vld2jl4zhfYIp5Yqudg root@ip-10-0-1-111 (ECDSA)
ec2: 256 SHA256:lZUSSdT6ealnLRk9Lg3Cw247WEs2H+zsmmOuNcgEHWk no comment (ED25519)
ec2: 2048 SHA256:h5pFGduiO6hrXdi/MNDEVWa1tm+Jd3lefIvnszIAOd8 root@ip-10-0-1-111 (RSA)
ec2: -----END SSH HOST KEY FINGERPRINTS-----
ec2: #############################################################
-----BEGIN SSH HOST KEY KEYS-----
ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBG5+n/uF3x3tDdDAXJ580183aT/LLIGZIaMp9/D+UkTo7Nhnl3PFFto2ldog/fJo4VFprNGxdKTEdyXMpSqSp78= root@ip-10-0-1-111
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMM+dpjy0NUDjxx9QGwkT4jxF7BQaAEWeCX01Fsx4igK 
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCu0GiMnss1Z4Qspdez7xyo/jhJYGuozxl5PpoAK3vWN48GBn2TE87JM9hIBHBdIWWyu2HMx/00qkquu8PTu/8vBWVVFpm5jrDvfgwwBDG9ATRpOtSQP6GCiNs8gTQC11DL+Sqw9fbSLTiR+jkgAHyLYyBI7QQi/zea66zUOXIEUvXbTFYrqo4jbrT5nxlln7r/a2JciaHhqU0H/xlQotyiOijAkYOE3N7G5/dg9T7SIWbaKXlZ4gfK6VtC6cIKlEv2f2giixNDL/ZUT/+2lA2FhlsF05FcosLH+u+uec8glLoHxRC+fd6T3XRx0aQxPjClhY3VvSlzTVJiX7V9204F root@ip-10-0-1-111
-----END SSH HOST KEY KEYS-----
Cloud-init v. 0.7.6 finished at Mon, 07 Jan 2019 09:26:22 +0000. Datasource DataSourceEc2.  Up 157.38 seconds

Amazon Linux AMI release 2018.03
Kernel 4.9.62-21.56.amzn1.x86_64 on an x86_64

ip-10-0-1-111 login:
```

**Comment by kglover29** [comment]
@mteichtahl we're you able to resolve this issue?

Thanks!

**Comment by ion-girloanta** [comment]
Got the error only for the first run on "wp plugin install w3-total-cache \n".  
Still didn't find the reason.

**Comment by fippy** [comment]
w3 Total Cache fails to install on stack creation for me too... The installation itself doesn't fail but the install of the plugin does. When I attempt to do it manually I get consistent 504 timeouts, even bypassing cloudfront and going directly to load balancer.

**Comment by mandersondesign** [comment]
Looks like this is resolved in a pull request, where you have to update that command to have allow-root:

```
wp plugin install w3-total-cache --allow-root
```
